# permissions for end users to view wbconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wbconnection-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wbconnection
    app.kubernetes.io/part-of: wbconnection
    app.kubernetes.io/managed-by: kustomize
  name: wbconnection-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - wbconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - wbconnections/status
  verbs:
  - get
