//go:build !ignore_autogenerated

/*
Copyright 2024 NTT Corporation , FUJITSU LIMITED

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllRequirementsInfo) DeepCopyInto(out *AllRequirementsInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllRequirementsInfo.
func (in *AllRequirementsInfo) DeepCopy() *AllRequirementsInfo {
	if in == nil {
		return nil
	}
	out := new(AllRequirementsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableInterfaceStruct) DeepCopyInto(out *AvailableInterfaceStruct) {
	*out = *in
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = make(map[string]DestinationStruct, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableInterfaceStruct.
func (in *AvailableInterfaceStruct) DeepCopy() *AvailableInterfaceStruct {
	if in == nil {
		return nil
	}
	out := new(AvailableInterfaceStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityInfo) DeepCopyInto(out *CapacityInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityInfo.
func (in *CapacityInfo) DeepCopy() *CapacityInfo {
	if in == nil {
		return nil
	}
	out := new(CapacityInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResource) DeepCopyInto(out *ComputeResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResource.
func (in *ComputeResource) DeepCopy() *ComputeResource {
	if in == nil {
		return nil
	}
	out := new(ComputeResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceList) DeepCopyInto(out *ComputeResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceList.
func (in *ComputeResourceList) DeepCopy() *ComputeResourceList {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceSpec) DeepCopyInto(out *ComputeResourceSpec) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]RegionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceSpec.
func (in *ComputeResourceSpec) DeepCopy() *ComputeResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeResourceStatus) DeepCopyInto(out *ComputeResourceStatus) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]RegionInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeResourceStatus.
func (in *ComputeResourceStatus) DeepCopy() *ComputeResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionIfStruct) DeepCopyInto(out *ConnectionIfStruct) {
	*out = *in
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.InterfaceList != nil {
		in, out := &in.InterfaceList, &out.InterfaceList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionIfStruct.
func (in *ConnectionIfStruct) DeepCopy() *ConnectionIfStruct {
	if in == nil {
		return nil
	}
	out := new(ConnectionIfStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionParamStruct) DeepCopyInto(out *ConnectionParamStruct) {
	*out = *in
	out.From = in.From
	out.To = in.To
	if in.UserParams != nil {
		in, out := &in.UserParams, &out.UserParams
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionParamStruct.
func (in *ConnectionParamStruct) DeepCopy() *ConnectionParamStruct {
	if in == nil {
		return nil
	}
	out := new(ConnectionParamStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionRequirementsInfo) DeepCopyInto(out *ConnectionRequirementsInfo) {
	*out = *in
	out.From = in.From
	out.To = in.To
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionRequirementsInfo.
func (in *ConnectionRequirementsInfo) DeepCopy() *ConnectionRequirementsInfo {
	if in == nil {
		return nil
	}
	out := new(ConnectionRequirementsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionScheduleInfo) DeepCopyInto(out *ConnectionScheduleInfo) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	in.To.DeepCopyInto(&out.To)
	if in.ConnectionPath != nil {
		in, out := &in.ConnectionPath, &out.ConnectionPath
		*out = make([]WBConnectionPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionScheduleInfo.
func (in *ConnectionScheduleInfo) DeepCopy() *ConnectionScheduleInfo {
	if in == nil {
		return nil
	}
	out := new(ConnectionScheduleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStruct) DeepCopyInto(out *ConnectionStruct) {
	*out = *in
	out.From = in.From
	out.To = in.To
	if in.CustomParameter != nil {
		in, out := &in.CustomParameter, &out.CustomParameter
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStruct.
func (in *ConnectionStruct) DeepCopy() *ConnectionStruct {
	if in == nil {
		return nil
	}
	out := new(ConnectionStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTarget) DeepCopyInto(out *ConnectionTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTarget.
func (in *ConnectionTarget) DeepCopy() *ConnectionTarget {
	if in == nil {
		return nil
	}
	out := new(ConnectionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTargetList) DeepCopyInto(out *ConnectionTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectionTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTargetList.
func (in *ConnectionTargetList) DeepCopy() *ConnectionTargetList {
	if in == nil {
		return nil
	}
	out := new(ConnectionTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTargetSpec) DeepCopyInto(out *ConnectionTargetSpec) {
	*out = *in
	out.IOResourceRef = in.IOResourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTargetSpec.
func (in *ConnectionTargetSpec) DeepCopy() *ConnectionTargetSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTargetStatus) DeepCopyInto(out *ConnectionTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTargetStatus.
func (in *ConnectionTargetStatus) DeepCopy() *ConnectionTargetStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionType) DeepCopyInto(out *ConnectionType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionType.
func (in *ConnectionType) DeepCopy() *ConnectionType {
	if in == nil {
		return nil
	}
	out := new(ConnectionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTypeList) DeepCopyInto(out *ConnectionTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConnectionType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTypeList.
func (in *ConnectionTypeList) DeepCopy() *ConnectionTypeList {
	if in == nil {
		return nil
	}
	out := new(ConnectionTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTypeSpec) DeepCopyInto(out *ConnectionTypeSpec) {
	*out = *in
	if in.ConnectionInfoNameSpaces != nil {
		in, out := &in.ConnectionInfoNameSpaces, &out.ConnectionInfoNameSpaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTypeSpec.
func (in *ConnectionTypeSpec) DeepCopy() *ConnectionTypeSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTypeStatus) DeepCopyInto(out *ConnectionTypeStatus) {
	*out = *in
	if in.AvailableInterfaces != nil {
		in, out := &in.AvailableInterfaces, &out.AvailableInterfaces
		*out = make(map[string]AvailableInterfaceStruct, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTypeStatus.
func (in *ConnectionTypeStatus) DeepCopy() *ConnectionTypeStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlow) DeepCopyInto(out *DataFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlow.
func (in *DataFlow) DeepCopy() *DataFlow {
	if in == nil {
		return nil
	}
	out := new(DataFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowList) DeepCopyInto(out *DataFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowList.
func (in *DataFlowList) DeepCopy() *DataFlowList {
	if in == nil {
		return nil
	}
	out := new(DataFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowRequirementsStruct) DeepCopyInto(out *DataFlowRequirementsStruct) {
	*out = *in
	if in.All != nil {
		in, out := &in.All, &out.All
		*out = new(AllRequirementsInfo)
		**out = **in
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]FunctionRequirementsInfo, len(*in))
		copy(*out, *in)
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]ConnectionRequirementsInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowRequirementsStruct.
func (in *DataFlowRequirementsStruct) DeepCopy() *DataFlowRequirementsStruct {
	if in == nil {
		return nil
	}
	out := new(DataFlowRequirementsStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowSpec) DeepCopyInto(out *DataFlowSpec) {
	*out = *in
	out.FunctionChainRef = in.FunctionChainRef
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.StartPoint != nil {
		in, out := &in.StartPoint, &out.StartPoint
		*out = new(StartEndPoint)
		**out = **in
	}
	if in.EndPoint != nil {
		in, out := &in.EndPoint, &out.EndPoint
		*out = new(StartEndPoint)
		**out = **in
	}
	if in.FunctionUserParameter != nil {
		in, out := &in.FunctionUserParameter, &out.FunctionUserParameter
		*out = make([]FunctionParamStruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectionUserParameter != nil {
		in, out := &in.ConnectionUserParameter, &out.ConnectionUserParameter
		*out = make([]ConnectionParamStruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(DataFlowRequirementsStruct)
		(*in).DeepCopyInto(*out)
	}
	if in.UserRequirement != nil {
		in, out := &in.UserRequirement, &out.UserRequirement
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowSpec.
func (in *DataFlowSpec) DeepCopy() *DataFlowSpec {
	if in == nil {
		return nil
	}
	out := new(DataFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowStatus) DeepCopyInto(out *DataFlowStatus) {
	*out = *in
	if in.FunctionChain != nil {
		in, out := &in.FunctionChain, &out.FunctionChain
		*out = new(FunctionChain)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionType != nil {
		in, out := &in.FunctionType, &out.FunctionType
		*out = make([]*FunctionType, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FunctionType)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ConnectionType != nil {
		in, out := &in.ConnectionType, &out.ConnectionType
		*out = make([]*ConnectionType, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ConnectionType)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ScheduledFunctions != nil {
		in, out := &in.ScheduledFunctions, &out.ScheduledFunctions
		*out = make(map[string]FunctionScheduleInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ScheduledConnections != nil {
		in, out := &in.ScheduledConnections, &out.ScheduledConnections
		*out = make([]ConnectionScheduleInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowStatus.
func (in *DataFlowStatus) DeepCopy() *DataFlowStatus {
	if in == nil {
		return nil
	}
	out := new(DataFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationStruct) DeepCopyInto(out *DestinationStruct) {
	*out = *in
	if in.Route != nil {
		in, out := &in.Route, &out.Route
		*out = make([]RouteStruct, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationStruct.
func (in *DestinationStruct) DeepCopy() *DestinationStruct {
	if in == nil {
		return nil
	}
	out := new(DestinationStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInfo) DeepCopyInto(out *DeviceInfo) {
	*out = *in
	if in.RegionName != nil {
		in, out := &in.RegionName, &out.RegionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInfo.
func (in *DeviceInfo) DeepCopy() *DeviceInfo {
	if in == nil {
		return nil
	}
	out := new(DeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityInfo) DeepCopyInto(out *EntityInfo) {
	*out = *in
	if in.LocationInfo != nil {
		in, out := &in.LocationInfo, &out.LocationInfo
		*out = new(LocationInfo)
		**out = **in
	}
	if in.CapacityInfo != nil {
		in, out := &in.CapacityInfo, &out.CapacityInfo
		*out = new(CapacityInfo)
		**out = **in
	}
	if in.NodeInfo != nil {
		in, out := &in.NodeInfo, &out.NodeInfo
		*out = new(NodeInfo)
		**out = **in
	}
	if in.DeviceInfo != nil {
		in, out := &in.DeviceInfo, &out.DeviceInfo
		*out = new(DeviceInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.InterfaceInfo != nil {
		in, out := &in.InterfaceInfo, &out.InterfaceInfo
		*out = new(InterfaceInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkInfo != nil {
		in, out := &in.NetworkInfo, &out.NetworkInfo
		*out = new(NetworkInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityInfo.
func (in *EntityInfo) DeepCopy() *EntityInfo {
	if in == nil {
		return nil
	}
	out := new(EntityInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromToFunction) DeepCopyInto(out *FromToFunction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromToFunction.
func (in *FromToFunction) DeepCopy() *FromToFunction {
	if in == nil {
		return nil
	}
	out := new(FromToFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromToFunctionInfo) DeepCopyInto(out *FromToFunctionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromToFunctionInfo.
func (in *FromToFunctionInfo) DeepCopy() *FromToFunctionInfo {
	if in == nil {
		return nil
	}
	out := new(FromToFunctionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromToFunctionScheduleInfo) DeepCopyInto(out *FromToFunctionScheduleInfo) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.InterfaceType != nil {
		in, out := &in.InterfaceType, &out.InterfaceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromToFunctionScheduleInfo.
func (in *FromToFunctionScheduleInfo) DeepCopy() *FromToFunctionScheduleInfo {
	if in == nil {
		return nil
	}
	out := new(FromToFunctionScheduleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromToWBFunction) DeepCopyInto(out *FromToWBFunction) {
	*out = *in
	out.WBFunctionRef = in.WBFunctionRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromToWBFunction.
func (in *FromToWBFunction) DeepCopy() *FromToWBFunction {
	if in == nil {
		return nil
	}
	out := new(FromToWBFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionCapStruct) DeepCopyInto(out *FunctionCapStruct) {
	*out = *in
	if in.MaxDataFlows != nil {
		in, out := &in.MaxDataFlows, &out.MaxDataFlows
		*out = new(int32)
		**out = **in
	}
	if in.CurrentDataFlows != nil {
		in, out := &in.CurrentDataFlows, &out.CurrentDataFlows
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
	if in.CurrentCapacity != nil {
		in, out := &in.CurrentCapacity, &out.CurrentCapacity
		*out = new(int32)
		**out = **in
	}
	if in.MaxTimeSlicingSeconds != nil {
		in, out := &in.MaxTimeSlicingSeconds, &out.MaxTimeSlicingSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CurrentTimeSlicingSeconds != nil {
		in, out := &in.CurrentTimeSlicingSeconds, &out.CurrentTimeSlicingSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionCapStruct.
func (in *FunctionCapStruct) DeepCopy() *FunctionCapStruct {
	if in == nil {
		return nil
	}
	out := new(FunctionCapStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionChain) DeepCopyInto(out *FunctionChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionChain.
func (in *FunctionChain) DeepCopy() *FunctionChain {
	if in == nil {
		return nil
	}
	out := new(FunctionChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionChainList) DeepCopyInto(out *FunctionChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionChainList.
func (in *FunctionChainList) DeepCopy() *FunctionChainList {
	if in == nil {
		return nil
	}
	out := new(FunctionChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionChainSpec) DeepCopyInto(out *FunctionChainSpec) {
	*out = *in
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make(map[string]FunctionStruct, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]ConnectionStruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionChainSpec.
func (in *FunctionChainSpec) DeepCopy() *FunctionChainSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionChainStatus) DeepCopyInto(out *FunctionChainStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionChainStatus.
func (in *FunctionChainStatus) DeepCopy() *FunctionChainStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionInfrastruct) DeepCopyInto(out *FunctionInfrastruct) {
	*out = *in
	if in.MaxDataFlows != nil {
		in, out := &in.MaxDataFlows, &out.MaxDataFlows
		*out = new(int32)
		**out = **in
	}
	if in.CurrentDataFlows != nil {
		in, out := &in.CurrentDataFlows, &out.CurrentDataFlows
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
	if in.CurrentCapacity != nil {
		in, out := &in.CurrentCapacity, &out.CurrentCapacity
		*out = new(int32)
		**out = **in
	}
	if in.MaxTimeSlicingSeconds != nil {
		in, out := &in.MaxTimeSlicingSeconds, &out.MaxTimeSlicingSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CurrentTimeSlicingSeconds != nil {
		in, out := &in.CurrentTimeSlicingSeconds, &out.CurrentTimeSlicingSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionInfrastruct.
func (in *FunctionInfrastruct) DeepCopy() *FunctionInfrastruct {
	if in == nil {
		return nil
	}
	out := new(FunctionInfrastruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionParamStruct) DeepCopyInto(out *FunctionParamStruct) {
	*out = *in
	if in.UserParams != nil {
		in, out := &in.UserParams, &out.UserParams
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionParamStruct.
func (in *FunctionParamStruct) DeepCopy() *FunctionParamStruct {
	if in == nil {
		return nil
	}
	out := new(FunctionParamStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionRequirementsInfo) DeepCopyInto(out *FunctionRequirementsInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionRequirementsInfo.
func (in *FunctionRequirementsInfo) DeepCopy() *FunctionRequirementsInfo {
	if in == nil {
		return nil
	}
	out := new(FunctionRequirementsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionScheduleInfo) DeepCopyInto(out *FunctionScheduleInfo) {
	*out = *in
	if in.FunctionIndex != nil {
		in, out := &in.FunctionIndex, &out.FunctionIndex
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionScheduleInfo.
func (in *FunctionScheduleInfo) DeepCopy() *FunctionScheduleInfo {
	if in == nil {
		return nil
	}
	out := new(FunctionScheduleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStruct) DeepCopyInto(out *FunctionStruct) {
	*out = *in
	if in.CustomParameter != nil {
		in, out := &in.CustomParameter, &out.CustomParameter
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStruct.
func (in *FunctionStruct) DeepCopy() *FunctionStruct {
	if in == nil {
		return nil
	}
	out := new(FunctionStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTarget) DeepCopyInto(out *FunctionTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTarget.
func (in *FunctionTarget) DeepCopy() *FunctionTarget {
	if in == nil {
		return nil
	}
	out := new(FunctionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTargetList) DeepCopyInto(out *FunctionTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTargetList.
func (in *FunctionTargetList) DeepCopy() *FunctionTargetList {
	if in == nil {
		return nil
	}
	out := new(FunctionTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTargetSpec) DeepCopyInto(out *FunctionTargetSpec) {
	*out = *in
	out.ComputeResourceRef = in.ComputeResourceRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTargetSpec.
func (in *FunctionTargetSpec) DeepCopy() *FunctionTargetSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTargetStatus) DeepCopyInto(out *FunctionTargetStatus) {
	*out = *in
	if in.MaxFunctions != nil {
		in, out := &in.MaxFunctions, &out.MaxFunctions
		*out = new(int32)
		**out = **in
	}
	if in.CurrentFunctions != nil {
		in, out := &in.CurrentFunctions, &out.CurrentFunctions
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
	if in.CurrentCapacity != nil {
		in, out := &in.CurrentCapacity, &out.CurrentCapacity
		*out = new(int32)
		**out = **in
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]FunctionCapStruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTargetStatus.
func (in *FunctionTargetStatus) DeepCopy() *FunctionTargetStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionType) DeepCopyInto(out *FunctionType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionType.
func (in *FunctionType) DeepCopy() *FunctionType {
	if in == nil {
		return nil
	}
	out := new(FunctionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTypeList) DeepCopyInto(out *FunctionTypeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTypeList.
func (in *FunctionTypeList) DeepCopy() *FunctionTypeList {
	if in == nil {
		return nil
	}
	out := new(FunctionTypeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTypeSpec) DeepCopyInto(out *FunctionTypeSpec) {
	*out = *in
	out.FunctionInfoCMRef = in.FunctionInfoCMRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTypeSpec.
func (in *FunctionTypeSpec) DeepCopy() *FunctionTypeSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionTypeStatus) DeepCopyInto(out *FunctionTypeStatus) {
	*out = *in
	if in.RegionTypeCandidates != nil {
		in, out := &in.RegionTypeCandidates, &out.RegionTypeCandidates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecommendConnection != nil {
		in, out := &in.RecommendConnection, &out.RecommendConnection
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionTypeStatus.
func (in *FunctionTypeStatus) DeepCopy() *FunctionTypeStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionTypeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceInfo) DeepCopyInto(out *InterfaceInfo) {
	*out = *in
	if in.DeviceType != nil {
		in, out := &in.DeviceType, &out.DeviceType
		*out = new(string)
		**out = **in
	}
	if in.DeviceIndex != nil {
		in, out := &in.DeviceIndex, &out.DeviceIndex
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceInfo.
func (in *InterfaceInfo) DeepCopy() *InterfaceInfo {
	if in == nil {
		return nil
	}
	out := new(InterfaceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationInfo) DeepCopyInto(out *LocationInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationInfo.
func (in *LocationInfo) DeepCopy() *LocationInfo {
	if in == nil {
		return nil
	}
	out := new(LocationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfo) DeepCopyInto(out *NetworkInfo) {
	*out = *in
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfo.
func (in *NetworkInfo) DeepCopy() *NetworkInfo {
	if in == nil {
		return nil
	}
	out := new(NetworkInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionInfo) DeepCopyInto(out *RegionInfo) {
	*out = *in
	if in.DeviceUUID != nil {
		in, out := &in.DeviceUUID, &out.DeviceUUID
		*out = new(string)
		**out = **in
	}
	if in.MaxFunctions != nil {
		in, out := &in.MaxFunctions, &out.MaxFunctions
		*out = new(int32)
		**out = **in
	}
	if in.CurrentFunctions != nil {
		in, out := &in.CurrentFunctions, &out.CurrentFunctions
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
	if in.CurrentCapacity != nil {
		in, out := &in.CurrentCapacity, &out.CurrentCapacity
		*out = new(int32)
		**out = **in
	}
	if in.MaxTimeSlicingSeconds != nil {
		in, out := &in.MaxTimeSlicingSeconds, &out.MaxTimeSlicingSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CurrentTimeSlicingSeconds != nil {
		in, out := &in.CurrentTimeSlicingSeconds, &out.CurrentTimeSlicingSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]FunctionInfrastruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionInfo.
func (in *RegionInfo) DeepCopy() *RegionInfo {
	if in == nil {
		return nil
	}
	out := new(RegionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationInfo) DeepCopyInto(out *RelationInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationInfo.
func (in *RelationInfo) DeepCopy() *RelationInfo {
	if in == nil {
		return nil
	}
	out := new(RelationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteStruct) DeepCopyInto(out *RouteStruct) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteStruct.
func (in *RouteStruct) DeepCopy() *RouteStruct {
	if in == nil {
		return nil
	}
	out := new(RouteStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingData) DeepCopyInto(out *SchedulingData) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingData.
func (in *SchedulingData) DeepCopy() *SchedulingData {
	if in == nil {
		return nil
	}
	out := new(SchedulingData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingData) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingDataList) DeepCopyInto(out *SchedulingDataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchedulingData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingDataList.
func (in *SchedulingDataList) DeepCopy() *SchedulingDataList {
	if in == nil {
		return nil
	}
	out := new(SchedulingDataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulingDataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingDataSpec) DeepCopyInto(out *SchedulingDataSpec) {
	*out = *in
	if in.FilterPipeline != nil {
		in, out := &in.FilterPipeline, &out.FilterPipeline
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingDataSpec.
func (in *SchedulingDataSpec) DeepCopy() *SchedulingDataSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingDataStatus) DeepCopyInto(out *SchedulingDataStatus) {
	*out = *in
	if in.CurrentFilterIndex != nil {
		in, out := &in.CurrentFilterIndex, &out.CurrentFilterIndex
		*out = new(int32)
		**out = **in
	}
	if in.TypeCombinations != nil {
		in, out := &in.TypeCombinations, &out.TypeCombinations
		*out = make([]TypeCombinationStruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetCombinations != nil {
		in, out := &in.TargetCombinations, &out.TargetCombinations
		*out = make([]TargetCombinationStruct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingDataStatus.
func (in *SchedulingDataStatus) DeepCopy() *SchedulingDataStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulingDataStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartEndPoint) DeepCopyInto(out *StartEndPoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartEndPoint.
func (in *StartEndPoint) DeepCopy() *StartEndPoint {
	if in == nil {
		return nil
	}
	out := new(StartEndPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetCombinationStruct) DeepCopyInto(out *TargetCombinationStruct) {
	*out = *in
	if in.ScheduledFunctions != nil {
		in, out := &in.ScheduledFunctions, &out.ScheduledFunctions
		*out = make(map[string]FunctionScheduleInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ScheduledConnections != nil {
		in, out := &in.ScheduledConnections, &out.ScheduledConnections
		*out = make([]ConnectionScheduleInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetCombinationStruct.
func (in *TargetCombinationStruct) DeepCopy() *TargetCombinationStruct {
	if in == nil {
		return nil
	}
	out := new(TargetCombinationStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfo) DeepCopyInto(out *TopologyInfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfo.
func (in *TopologyInfo) DeepCopy() *TopologyInfo {
	if in == nil {
		return nil
	}
	out := new(TopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopologyInfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfoList) DeepCopyInto(out *TopologyInfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopologyInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfoList.
func (in *TopologyInfoList) DeepCopy() *TopologyInfoList {
	if in == nil {
		return nil
	}
	out := new(TopologyInfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopologyInfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfoSpec) DeepCopyInto(out *TopologyInfoSpec) {
	*out = *in
	if in.TopologyDataCMRef != nil {
		in, out := &in.TopologyDataCMRef, &out.TopologyDataCMRef
		*out = make([]WBNamespacedName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfoSpec.
func (in *TopologyInfoSpec) DeepCopy() *TopologyInfoSpec {
	if in == nil {
		return nil
	}
	out := new(TopologyInfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfoStatus) DeepCopyInto(out *TopologyInfoStatus) {
	*out = *in
	if in.Entities != nil {
		in, out := &in.Entities, &out.Entities
		*out = make([]EntityInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Relations != nil {
		in, out := &in.Relations, &out.Relations
		*out = make([]RelationInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfoStatus.
func (in *TopologyInfoStatus) DeepCopy() *TopologyInfoStatus {
	if in == nil {
		return nil
	}
	out := new(TopologyInfoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeCombinationStruct) DeepCopyInto(out *TypeCombinationStruct) {
	*out = *in
	if in.DeviceTypes != nil {
		in, out := &in.DeviceTypes, &out.DeviceTypes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConnectionTypes != nil {
		in, out := &in.ConnectionTypes, &out.ConnectionTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeCombinationStruct.
func (in *TypeCombinationStruct) DeepCopy() *TypeCombinationStruct {
	if in == nil {
		return nil
	}
	out := new(TypeCombinationStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnection) DeepCopyInto(out *WBConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnection.
func (in *WBConnection) DeepCopy() *WBConnection {
	if in == nil {
		return nil
	}
	out := new(WBConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WBConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionEdge) DeepCopyInto(out *WBConnectionEdge) {
	*out = *in
	out.From = in.From
	out.To = in.To
	if in.IntParams != nil {
		in, out := &in.IntParams, &out.IntParams
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StrParams != nil {
		in, out := &in.StrParams, &out.StrParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionEdge.
func (in *WBConnectionEdge) DeepCopy() *WBConnectionEdge {
	if in == nil {
		return nil
	}
	out := new(WBConnectionEdge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionIO) DeepCopyInto(out *WBConnectionIO) {
	*out = *in
	if in.IntParams != nil {
		in, out := &in.IntParams, &out.IntParams
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StrParams != nil {
		in, out := &in.StrParams, &out.StrParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionIO.
func (in *WBConnectionIO) DeepCopy() *WBConnectionIO {
	if in == nil {
		return nil
	}
	out := new(WBConnectionIO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionList) DeepCopyInto(out *WBConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WBConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionList.
func (in *WBConnectionList) DeepCopy() *WBConnectionList {
	if in == nil {
		return nil
	}
	out := new(WBConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WBConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionPath) DeepCopyInto(out *WBConnectionPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionPath.
func (in *WBConnectionPath) DeepCopy() *WBConnectionPath {
	if in == nil {
		return nil
	}
	out := new(WBConnectionPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionRequirementsInfo) DeepCopyInto(out *WBConnectionRequirementsInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionRequirementsInfo.
func (in *WBConnectionRequirementsInfo) DeepCopy() *WBConnectionRequirementsInfo {
	if in == nil {
		return nil
	}
	out := new(WBConnectionRequirementsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionSpec) DeepCopyInto(out *WBConnectionSpec) {
	*out = *in
	out.DataFlowRef = in.DataFlowRef
	if in.ConnectionPath != nil {
		in, out := &in.ConnectionPath, &out.ConnectionPath
		*out = make([]WBConnectionPath, len(*in))
		copy(*out, *in)
	}
	out.From = in.From
	out.To = in.To
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(WBConnectionRequirementsInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionSpec.
func (in *WBConnectionSpec) DeepCopy() *WBConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(WBConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBConnectionStatus) DeepCopyInto(out *WBConnectionStatus) {
	*out = *in
	out.DataFlowRef = in.DataFlowRef
	if in.ConnectionPath != nil {
		in, out := &in.ConnectionPath, &out.ConnectionPath
		*out = make([]WBConnectionPath, len(*in))
		copy(*out, *in)
	}
	out.From = in.From
	out.To = in.To
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SatisfiedRequirements != nil {
		in, out := &in.SatisfiedRequirements, &out.SatisfiedRequirements
		*out = new(WBConnectionRequirementsInfo)
		**out = **in
	}
	if in.IOs != nil {
		in, out := &in.IOs, &out.IOs
		*out = make(map[string]WBConnectionIO, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]WBConnectionEdge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBConnectionStatus.
func (in *WBConnectionStatus) DeepCopy() *WBConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(WBConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBFunction) DeepCopyInto(out *WBFunction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBFunction.
func (in *WBFunction) DeepCopy() *WBFunction {
	if in == nil {
		return nil
	}
	out := new(WBFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WBFunction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBFunctionList) DeepCopyInto(out *WBFunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WBFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBFunctionList.
func (in *WBFunctionList) DeepCopy() *WBFunctionList {
	if in == nil {
		return nil
	}
	out := new(WBFunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WBFunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBFunctionRequirementsInfo) DeepCopyInto(out *WBFunctionRequirementsInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBFunctionRequirementsInfo.
func (in *WBFunctionRequirementsInfo) DeepCopy() *WBFunctionRequirementsInfo {
	if in == nil {
		return nil
	}
	out := new(WBFunctionRequirementsInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBFunctionSpec) DeepCopyInto(out *WBFunctionSpec) {
	*out = *in
	out.DataFlowRef = in.DataFlowRef
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.FunctionIndex != nil {
		in, out := &in.FunctionIndex, &out.FunctionIndex
		*out = new(int32)
		**out = **in
	}
	if in.InputInterface != nil {
		in, out := &in.InputInterface, &out.InputInterface
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OutputInterface != nil {
		in, out := &in.OutputInterface, &out.OutputInterface
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PreviousWBFunctions != nil {
		in, out := &in.PreviousWBFunctions, &out.PreviousWBFunctions
		*out = make(map[string]FromToWBFunction, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NextWBFunctions != nil {
		in, out := &in.NextWBFunctions, &out.NextWBFunctions
		*out = make(map[string]FromToWBFunction, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxDataFlows != nil {
		in, out := &in.MaxDataFlows, &out.MaxDataFlows
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(WBFunctionRequirementsInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBFunctionSpec.
func (in *WBFunctionSpec) DeepCopy() *WBFunctionSpec {
	if in == nil {
		return nil
	}
	out := new(WBFunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBFunctionStatus) DeepCopyInto(out *WBFunctionStatus) {
	*out = *in
	out.DataFlowRef = in.DataFlowRef
	if in.InputInterface != nil {
		in, out := &in.InputInterface, &out.InputInterface
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OutputInterface != nil {
		in, out := &in.OutputInterface, &out.OutputInterface
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PreviousWBFunctions != nil {
		in, out := &in.PreviousWBFunctions, &out.PreviousWBFunctions
		*out = make(map[string]FromToWBFunction, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NextWBFunctions != nil {
		in, out := &in.NextWBFunctions, &out.NextWBFunctions
		*out = make(map[string]FromToWBFunction, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxDataFlows != nil {
		in, out := &in.MaxDataFlows, &out.MaxDataFlows
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = new(int32)
		**out = **in
	}
	out.SatisfiedRequirements = in.SatisfiedRequirements
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBFunctionStatus.
func (in *WBFunctionStatus) DeepCopy() *WBFunctionStatus {
	if in == nil {
		return nil
	}
	out := new(WBFunctionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBNamespacedName) DeepCopyInto(out *WBNamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBNamespacedName.
func (in *WBNamespacedName) DeepCopy() *WBNamespacedName {
	if in == nil {
		return nil
	}
	out := new(WBNamespacedName)
	in.DeepCopyInto(out)
	return out
}
