# permissions for end users to view ethernetconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ethernetconnection-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ethernetconnection
    app.kubernetes.io/part-of: ethernetconnection
    app.kubernetes.io/managed-by: kustomize
  name: ethernetconnection-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - ethernetconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - ethernetconnections/status
  verbs:
  - get
