# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/example.com_dataflows.yaml
- bases/example.com_wbfunctions.yaml
- bases/example.com_wbconnections.yaml
- bases/example.com_functionchains.yaml
- bases/example.com_functiontypes.yaml
- bases/example.com_connectiontypes.yaml
- bases/example.com_functiontargets.yaml
- bases/example.com_connectiontargets.yaml
- bases/example.com_computeresources.yaml
- bases/example.com_schedulingdata.yaml
#- bases/example.com_ioresources.yaml
- bases/example.com_topologyinfos.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_dataflows.yaml
#- patches/webhook_in_wbfunctions.yaml
#- patches/webhook_in_wbconnections.yaml
#- patches/webhook_in_functionchains.yaml
#- patches/webhook_in_functiontypes.yaml
#- patches/webhook_in_connectiontypes.yaml
#- patches/webhook_in_functiontargets.yaml
#- patches/webhook_in_connectiontargets.yaml
#- patches/webhook_in_computeresources.yaml
#- patches/webhook_in_topologyinfos.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_dataflows.yaml
#- patches/cainjection_in_wbfunctions.yaml
#- patches/cainjection_in_wbconnections.yaml
#- patches/cainjection_in_functionchains.yaml
#- patches/cainjection_in_functiontypes.yaml
#- patches/cainjection_in_connectiontypes.yaml
#- patches/cainjection_in_functiontargets.yaml
#- patches/cainjection_in_connectiontargets.yaml
#- patches/cainjection_in_computeresources.yaml
#- patches/cainjection_in_topologyinfos.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
