# permissions for end users to edit deviceinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deviceinfo-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deviceinfo
    app.kubernetes.io/part-of: deviceinfo
    app.kubernetes.io/managed-by: kustomize
  name: deviceinfo-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - deviceinfos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - deviceinfos/status
  verbs:
  - get
