# permissions for end users to view deviceinfos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deviceinfo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deviceinfo
    app.kubernetes.io/part-of: deviceinfo
    app.kubernetes.io/managed-by: kustomize
  name: deviceinfo-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - deviceinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - deviceinfos/status
  verbs:
  - get
