//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package request

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FPGAReconfiguration) DeepCopyInto(out *FPGAReconfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FPGAReconfiguration.
func (in *FPGAReconfiguration) DeepCopy() *FPGAReconfiguration {
	if in == nil {
		return nil
	}
	out := new(FPGAReconfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FPGAReconfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FPGAReconfigurationList) DeepCopyInto(out *FPGAReconfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FPGAReconfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FPGAReconfigurationList.
func (in *FPGAReconfigurationList) DeepCopy() *FPGAReconfigurationList {
	if in == nil {
		return nil
	}
	out := new(FPGAReconfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FPGAReconfigurationSpec) DeepCopyInto(out *FPGAReconfigurationSpec) {
	*out = *in
	if in.FPGAResetFlag != nil {
		in, out := &in.FPGAResetFlag, &out.FPGAResetFlag
		*out = new(bool)
		**out = **in
	}
	if in.ChildBsResetFlag != nil {
		in, out := &in.ChildBsResetFlag, &out.ChildBsResetFlag
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FPGAReconfigurationSpec.
func (in *FPGAReconfigurationSpec) DeepCopy() *FPGAReconfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(FPGAReconfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FPGAReconfigurationStatus) DeepCopyInto(out *FPGAReconfigurationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FPGAReconfigurationStatus.
func (in *FPGAReconfigurationStatus) DeepCopy() *FPGAReconfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(FPGAReconfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
