# permissions for end users to view connectiontargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: connectiontarget-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: whitebox-k8s-flowctrl
    app.kubernetes.io/part-of: whitebox-k8s-flowctrl
    app.kubernetes.io/managed-by: kustomize
  name: connectiontarget-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - connectiontargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - connectiontargets/status
  verbs:
  - get
