# permissions for end users to edit dataflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dataflow-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: whitebox-k8s-flowctrl
    app.kubernetes.io/part-of: whitebox-k8s-flowctrl
    app.kubernetes.io/managed-by: kustomize
  name: dataflow-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - dataflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - dataflows/status
  verbs:
  - get
