# permissions for end users to view fpgafunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fpgafunction-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fpgafunction
    app.kubernetes.io/part-of: fpgafunction
    app.kubernetes.io/managed-by: kustomize
  name: fpgafunction-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - fpgafunctions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - fpgafunctions/status
  verbs:
  - get
