---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - cpufunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - cpufunctions/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - cpufunctions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - example.com
  resources:
  - deviceinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - deviceinfoes/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - deviceinfoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - example.com
  resources:
  - fpgafunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - fpgafunctions/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - fpgafunctions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - example.com
  resources:
  - gpufunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - gpufunctions/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - gpufunctions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - example.com
  resources:
  - wbfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - wbfunctions/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - wbfunctions/status
  verbs:
  - get
  - patch
  - update
