# permissions for end users to edit wbfunctions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wbfunction-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: wbfunction
    app.kubernetes.io/part-of: wbfunction
    app.kubernetes.io/managed-by: kustomize
  name: wbfunction-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - wbfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - wbfunctions/status
  verbs:
  - get
