# Original file is https://github.com/kubernetes/kubernetes/blob/release-1.30/hack/golangci.yaml

run:
  timeout: 30m
  skip-files: []

output:
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  # The default excludes disable the "should have comment or be unexported" check from revive.
  # We want that to be enabled, therefore we have to disable all default excludes and
  # add those back one-by-one that we want. See https://github.com/golangci/golangci-lint/issues/456#issuecomment-617470264
  exclude-use-default: false
  exclude:
    # staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore
    - ineffective break statement. Did you mean to break out of the outer loop

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # SSA Extract calls are allowed in tests.
    - linters:
        - forbidigo
      text: should not be used because managedFields was removed
      path: _test.go$

    # TODO(oscr) Remove these excluded directories and fix findings. Due to large amount of findings in different components
    # with different owners it's hard to fix everything in a single pr. This will therefore be done in multiple prs.
    - path: (pkg/volume/*|test/*|azure/*|pkg/cmd/wait*|request/bearertoken/*|metrics/*|filters/*)
      linters:
        - gocritic

    # This check currently has some false positives (https://github.com/nunnatsa/ginkgolinter/issues/91).
    - linters:
       - ginkgolinter
      text: use a function call in (Eventually|Consistently)

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507012435
    - linters:
        - gocritic
      text: "ifElseChain: rewrite if-else to switch statement"

    # Only packages listed here opt into the strict "exported symbols must be documented".
    #
    # Exclude texts from https://github.com/golangci/golangci-lint/blob/ab3c3cd69e602ff53bb4c3e2c188f0caeb80305d/pkg/config/issues.go#L11-L103
    - linters:
        - golint
        - revive
        - stylecheck
      text: comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form|comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form|exported (.+) should have comment( \(or a comment on this block\))? or be unexported|package comment should be of the form "(.+)...|comment on exported (.+) should be of the form "(.+)...|should have a package comment

    # The following issues were deemed "might be worth fixing, needs to be
    # decided on a case-by-case basis".  This was initially decided by a
    # majority of the developers who voted in
    # https://github.com/kubernetes/kubernetes/issues/117288 and may evolve
    # over time.

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507008918
    - linters:
        - gocritic
      text: "assignOp:"

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507016854
    - linters:
        - gosimple
      text: "S1002: should omit comparison to bool constant"

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507023980
    - linters:
        - gosimple
      text: "S1016: should convert opts .* instead of using struct literal"

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507026758
    - linters:
        - gosimple
      text: "S1033: unnecessary guard around call to delete"

    # Didn't make it into https://github.com/kubernetes/kubernetes/issues/117288.
    # Discussion on Slack concluded that "it's hard to have a universal policy for all
    # functions marked deprecated" and thus this can only be a hint which must
    # be considered on a case-by-case basis.
    - linters:
        - staticcheck
      text: "SA1019: .*is deprecated"

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507030071
    - linters:
        - stylecheck
      text: "ST1012: error var .* should have name of the form ErrFoo"

    # https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507031224
    - linters:
        - stylecheck
      text: "ST1023: should omit type .* from declaration; it will be inferred from the right-hand side"

linters:
  disable-all: true
  enable: # please keep this alphabetized
    - ginkgolinter
    - gocritic
    - govet
    - ineffassign
    - revive
    - staticcheck
    - stylecheck
    - unused

linters-settings: # please keep this alphabetized
  custom:
  gocritic:
    enabled-checks:
      - equalFold
      - boolExprSimplify
  revive:
    # Only these rules are enabled.
    rules:
      - name: exported
        arguments:
        - disableStutteringCheck
  staticcheck:
    checks:
      - "all"
      - "-SA1019"  # TODO(fix) Using a deprecated function, variable, constant or field
      - "-SA2002"  # TODO(fix) Called testing.T.FailNow or SkipNow in a goroutine, which isn’t allowed
  stylecheck:
    checks:
      - "ST1019"   # Importing the same package multiple times
