apiVersion: v1
kind: Pod
metadata:
  name: cpu-decode
spec:
  hostNetwork: true
  hostIPC: true
  containers:
  - name: decode
    image: localhost/host_decode:latest
    command: ["/bin/sleep", "3650d"]
    env:
    - name: DECENV_VIDEOSRC_IPA
      value: 10.38.119.22
    - name: DECENV_VIDEOSRC_PORT
      value: "8554"
    - name: DECENV_FRAME_FPS
      value: "15"
    - name: DECENV_FRAME_WIDTH
      value: "3840"
    - name: DECENV_FRAME_HEIGHT
      value: "2160"
    - name: DECENV_OUTDST_PROTOCOL
      value: TCP
    - name: DECENV_OUTDST_IPA
      value: 10.38.119.20
    - name: DECENV_OUTDST_PORT
      value: "8888"
    securityContext:
      privileged: true
  affinity:
    nodeAffinity:  
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - wbta06