apiVersion: v1
kind: Pod
metadata:
  name: tester
spec:
  containers:
  - name: tester
    image: localhost/filter-resize-cpu:1.0.0
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
  hostNetwork: true      
  affinity:
    nodeAffinity:  
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - wbtamon01